#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=baseline_test
#SBATCH --ntasks=1
#SBATCH --time=00:30:00
#SBATCH --mem=32000M
#SBATCH --output=baseline_test.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate dl2023
# Run your code
srun python -u train.py --train_dataset cifar100 --save_model_name cifar100_baseline_wrn_28_2.pt --data_root ./data/ --alpha 0 --beta 0