 #!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=LICO_test
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=LICO_test.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment (note that you need to add transformers library to dl2023 for this to work)
source activate dl2023
# Run your code
srun python -u train.py


