#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=lico
#SBATCH --ntasks=1
#SBATCH --time=02:30:00
#SBATCH --mem=32000M
#SBATCH --output=fixed_lico.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate dl2023
# Run your code
srun python -u train.py --save_model_name fixed_CIFAR10_full_data_seed42.pt --data_root ./data/ --alpha 10 --beta 1 --weight_decay 5e-4 --seed 42